# Generated by Django 2.1.3 on 2018-11-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='icc_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='net',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
